language: node_js
node_js:
- node
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: DwZ4JU2bYcHSymCj9HfXYJBM2mLQZ1YbFeVfimngOWjL4SMQNgrxr5bTg4+PM39nUJN4S11D/yM//fd1c3sXQz/4lTW/NaBc8//tmGvRfwoekDz5+BWVaGMFUqUU4pCqmEbDZaVtjTMrUXGH57D2SORR7i8AERSeRjfKiC46Z09rAoYXVaRSsU/izV7n8rSdHzUEayXbvNyIGegz7eoq51bfTusEYhZZ0C0NQpTzXaROj3X6Vtr1UTBt/BKxjifRBSoPZpak1rejsqwNCMbHCqRtpEjwBRyuCiDvktP2zO+Iz9V6fjNRuk4E10w40qtjBqLdhoJmF8ZvUpYPjVMqUDg15VFLsBg+XHaRR2RlHGYbbp9XY803Vxl+HpZ+zNii3mN169etviEuY6yoDVZJMomxfMJbR6NsXNiGrVMD2qUgWpJd7rTvsWg+2eOvw7GISblA5AmPojDzB9653WHy3Q4JlAJpb3WWD1tcYLyotm7vgvfx7YWU5YDr7ekVHG6U6wo3Km8EtFQUtJCCqaRCER+lsFYLYAp0scfHrzobwtATxqjUwQaTxxYOjerICksJVwZl0CcIIgtrzAHaXlh2W423EDjDXRBp4StDcEu6T9Q3huJQhsxi8iYVECJifAcVdgFfsCi0QZVSAmFZt9bmaXNUYfxfNvEmfMZucohZA38=
  on:
    tags: true
    repo: up9cloud/graphql-tools-type-flat-object
    branch: master
